# Generated by Django 5.0.2 on 2024-04-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=14)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminimo')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('foto', models.ImageField(upload_to='alunos')),
            ],
        ),
    ]
