# Generated by Django 5.0.2 on 2024-02-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.CharField(choices=[('KG', 'Quilo'), ('UND', 'Unidade'), ('SACO', 'Saco')], default='UNIDADE', max_length=120),
        ),
    ]
