# Generated by Django 5.0.2 on 2024-02-26 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_categoria_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='habilitado',
            field=models.BooleanField(default=True, help_text='Se tá disponível para venda'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='vendas.produto')),
            ],
        ),
    ]
