# Generated by Django 5.0.2 on 2024-02-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clube_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='ano_fundacao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clube',
            name='tem_mundial',
            field=models.BooleanField(default=False),
        ),
    ]
