# Generated by Django 5.0.2 on 2024-02-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clube_ano_fundacao_clube_tem_mundial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='cores',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='clube',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('RS', 'Rio Grande do Sul'), ('RJ', 'Rio de Janeiro'), ('SP', 'São Paulo')], max_length=120, null=True),
        ),
    ]
