# Generated by Django 5.0.2 on 2024-03-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_clube_estado_clube_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='escudo',
            field=models.ImageField(null=True, upload_to='clubes'),
        ),
    ]
